const PERSONALITIES = {
  ENTP: {
    type: "ENTP",
    name: "辩论家",
    traits: ["好奇", "反常识", "爱波动"],
    strategy: "买入跨式 Long Straddle",
    line: "方向不重要，波动才是主角。",
    risk: "波动不够大，时间价值会慢慢流失。",
    note: "ENTP 不怕市场吵起来，反而怕市场太安静。跨式组合不押涨跌，押的是行情会不会真的闹出动静。",
    image: "./images/01_ENTP_辩论家_漫画版.png",
    color: "#00c8ff",
  },
  INTJ: {
    type: "INTJ",
    name: "建筑师",
    traits: ["规划", "冷静", "防守反击"],
    strategy: "保护性看跌 Protective Put",
    line: "先把地板铺好，再让仓位奔跑。",
    risk: "保险不是免费午餐，权利金会吃掉部分收益。",
    note: "INTJ 不喜欢裸奔式交易。先定义最坏情况，再让长期判断慢慢发挥。",
    image: "./images/02_INTJ_建筑师_海报版.png",
    color: "#8bdbff",
  },
  ESTP: {
    type: "ESTP",
    name: "企业家",
    traits: ["行动", "短线", "敢博弈"],
    strategy: "Gamma 短线交易 Gamma Trading",
    line: "越快的行情，越要先定义亏损。",
    risk: "节奏错了，交易成本和滑点会迅速放大。",
    note: "ESTP 喜欢快节奏，但期权里的快不是乱冲，而是用有限亏损去捕捉剧烈波动。",
    image: "./images/03_ESTP_企业家_海报版.png",
    color: "#ffb238",
  },
  ISTJ: {
    type: "ISTJ",
    name: "物流师",
    traits: ["纪律", "稳健", "价格敏感"],
    strategy: "现金担保卖 Put Cash-Secured Put",
    line: "价格不到位，我宁愿等。",
    risk: "标的大跌时，可能被动接货并承受浮亏。",
    note: "ISTJ 不急着追高，更像是在理想价格挂一张接货单，顺便收一点权利金。",
    image: "./images/04_ISTJ_物流师_海报版.png",
    color: "#75d19a",
  },
  ENFP: {
    type: "ENFP",
    name: "竞选者",
    traits: ["灵感", "弹性", "机会感"],
    strategy: "买入宽跨式 Long Strangle",
    line: "机会可能从任何一边冒出来。",
    risk: "需要足够大的方向突破，否则两边权利金都会消耗。",
    note: "ENFP 不想太早选边，他更愿意买一张不确定性的门票，等市场自己表态。",
    image: "./images/05_ENFP_竞选者.png",
    color: "#ff68c5",
  },
  ENTJ: {
    type: "ENTJ",
    name: "指挥官",
    traits: ["进攻", "目标", "控风险"],
    strategy: "牛市看涨价差 Bull Call Spread",
    line: "进攻要有目标，亏损要有边界。",
    risk: "收益上限被封顶，标的大涨时无法吃完整段。",
    note: "ENTJ 看多时不会只喊口号，他会把目标价、成本和最大亏损先摆在桌上。",
    image: "./images/06_ENTJ_指挥官.png",
    color: "#2ee6a6",
  },
  INTP: {
    type: "INTP",
    name: "逻辑学家",
    traits: ["模型", "拆解", "时间感"],
    strategy: "日历价差 Calendar Spread",
    line: "时间价值，是可以被研究的变量。",
    risk: "波动率曲面变化会让日历价差偏离预期。",
    note: "INTP 喜欢研究不同期限的定价差异，日历价差正好把时间变成一张实验台。",
    image: "./images/07_INTP_逻辑学家.png",
    color: "#9e8cff",
  },
  ESTJ: {
    type: "ESTJ",
    name: "总经理",
    traits: ["规则", "执行", "区间"],
    strategy: "铁鹰 Iron Condor",
    line: "把市场关进区间，再按纪律收租。",
    risk: "突破区间时亏损会扩大，必须提前设好处理规则。",
    note: "ESTJ 喜欢边界、流程和纪律，铁鹰策略正是把盈利区间和风险边界写清楚。",
    image: "./images/08_ESTJ_总经理.png",
    color: "#00b7ff",
  },
  INFJ: {
    type: "INFJ",
    name: "提倡者",
    traits: ["愿景", "边界", "守护"],
    strategy: "领口策略 Collar",
    line: "既想参与未来，也要守住底线。",
    risk: "保护下行的同时，也会牺牲一部分上行空间。",
    note: "INFJ 愿意相信长期故事，但不会忽略风险底线。Collar 很像给理想加一圈护栏。",
    image: "./images/09_INFJ_提倡者_老帅哥版.png",
    color: "#70f0ff",
  },
  INFP: {
    type: "INFP",
    name: "调停者",
    traits: ["信念", "想象", "轻仓"],
    strategy: "买入看涨 Long Call",
    line: "愿意为一个大故事付权利金。",
    risk: "判断方向和时间都要对，否则权利金可能归零。",
    note: "INFP 会被一个未来叙事打动，但 Long Call 至少把最坏亏损锁在权利金里。",
    image: "./images/10_INFP_调停者.png",
    color: "#d88cff",
  },
  ENFJ: {
    type: "ENFJ",
    name: "主人公",
    traits: ["组织", "平衡", "现金流"],
    strategy: "备兑看涨 Covered Call",
    line: "持有核心资产，也创造现金流。",
    risk: "标的大涨时可能被行权，错过部分上行收益。",
    note: "ENFJ 喜欢让资产组合更有秩序，备兑看涨就是在持仓上多安排一层现金流。",
    image: "./images/11_ENFJ_主人公.png",
    color: "#26d6b0",
  },
  ESFJ: {
    type: "ESFJ",
    name: "执政官",
    traits: ["稳定", "照顾", "现金流"],
    strategy: "看涨蝶式 Call Butterfly",
    line: "把情绪安顿在一个舒服区间里。",
    risk: "价格偏离目标区间太远，收益会明显下降。",
    note: "ESFJ 喜欢稳定、秩序和可照顾的边界，看涨蝶式更像给行情安排一个温和的舞台。",
    image: "./images/12_ESFJ_执政官.png",
    color: "#67d88d",
  },
  ISTP: {
    type: "ISTP",
    name: "鉴赏家",
    traits: ["实操", "冷静", "调仓"],
    strategy: "Delta 中性对冲 Delta Neutral",
    line: "像修机器一样调风险。",
    risk: "对冲频率、成本和跳空风险会影响最终效果。",
    note: "ISTP 擅长动手修正系统，Delta 中性对冲正是不断校准风险机器的过程。",
    image: "./images/13_ISTP_鉴赏家.png",
    color: "#39c7ff",
  },
  ISFP: {
    type: "ISFP",
    name: "探险家",
    traits: ["自由", "敏感", "轻成本"],
    strategy: "看跌价差 Bear Put Spread",
    line: "有防守观点，但不想成本太贵。",
    risk: "最大收益也被限制，适合明确区间内的下跌判断。",
    note: "ISFP 不喜欢笨重的仓位，Put Spread 用较低成本表达防守观点。",
    image: "./images/14_ISFP_探险家.png",
    color: "#ff8a5c",
  },
  ISFJ: {
    type: "ISFJ",
    name: "守卫者",
    traits: ["谨慎", "保护", "安全垫"],
    strategy: "买入看跌 Long Put",
    line: "先把风险挡在门外。",
    risk: "如果下跌没有发生，权利金可能归零。",
    note: "ISFJ 最在意资产别突然受伤。Long Put 很直接：花一笔确定成本，换一个下行保护的心理边界。",
    image: "./images/15_ISFJ_守卫者.png",
    color: "#78e6c2",
  },
  ESFP: {
    type: "ESFP",
    name: "表演者",
    traits: ["热情", "舞台", "爆发"],
    strategy: "看涨反比率价差 Call Ratio Backspread",
    line: "要么没事，要么就来一段大舞台。",
    risk: "小幅上涨反而可能最难受，比例和成本要控制。",
    note: "ESFP 喜欢爆发和舞台感。Call Ratio Backspread 更像为大幅上行准备聚光灯，但中间地带也要小心。",
    image: "./images/16_ESFP_表演者.png",
    color: "#ffcc4d",
  },
};

const QUESTIONS = [
  {
    axis: "E / I",
    text: "看到一只热门标的突然放量，你第一反应更像哪一种？",
    a: { text: "先去讨论区、群聊和盘口里感受市场情绪。", letter: "E" },
    b: { text: "先自己看图、看波动率和关键价位。", letter: "I" },
  },
  {
    axis: "S / N",
    text: "你更相信哪种交易线索？",
    a: { text: "成交量、波动率、支撑压力这些已经发生的数据。", letter: "S" },
    b: { text: "叙事变化、预期差和未来可能展开的大剧情。", letter: "N" },
  },
  {
    axis: "T / F",
    text: "一笔交易亏损后，你最先复盘什么？",
    a: { text: "逻辑有没有错，盈亏比和概率是否站得住。", letter: "T" },
    b: { text: "当时的感受、信念和风险承受是否匹配。", letter: "F" },
  },
  {
    axis: "J / P",
    text: "开仓前你更喜欢哪种状态？",
    a: { text: "入场、止损、止盈和调仓规则都先写好。", letter: "J" },
    b: { text: "先保留弹性，等市场走出来再调整。", letter: "P" },
  },
  {
    axis: "E / I",
    text: "面对财报、CPI、利率决议这类事件，你更倾向于？",
    a: { text: "喜欢观察市场共识和多人博弈。", letter: "E" },
    b: { text: "更愿意安静建模，判断事件波动是否被高估。", letter: "I" },
  },
  {
    axis: "S / N",
    text: "选择期权策略时，你更在意？",
    a: { text: "最大亏损、保证金、到期日、执行价这些具体参数。", letter: "S" },
    b: { text: "这笔策略背后的市场状态和不确定性结构。", letter: "N" },
  },
  {
    axis: "T / F",
    text: "朋友问你某个期权能不能买，你会先说？",
    a: { text: "先算波动率和盈亏结构，别凭感觉。", letter: "T" },
    b: { text: "先看你能不能承受这笔钱亏掉。", letter: "F" },
  },
  {
    axis: "J / P",
    text: "市场没有按计划走，你更倾向于？",
    a: { text: "按预设规则处理，不临场加戏。", letter: "J" },
    b: { text: "重新观察局面，如果结构变了就顺势改。", letter: "P" },
  },
  {
    axis: "E / I",
    text: "你更享受哪种交易环境？",
    a: { text: "信息流很热、观点交锋很激烈的市场。", letter: "E" },
    b: { text: "噪音较少，能慢慢拆解结构的市场。", letter: "I" },
  },
  {
    axis: "S / N",
    text: "看到一条波动率曲线，你更容易注意到？",
    a: { text: "哪一期限最贵、哪个执行价最异常。", letter: "S" },
    b: { text: "曲线背后暗示市场在害怕什么未来。", letter: "N" },
  },
  {
    axis: "T / F",
    text: "你更喜欢哪种交易理由？",
    a: { text: "赔率、胜率、波动率定价都能讲清楚。", letter: "T" },
    b: { text: "和自己的节奏、风险感受、长期信念一致。", letter: "F" },
  },
  {
    axis: "J / P",
    text: "你更讨厌哪种情况？",
    a: { text: "规则被打乱，仓位变得没有边界。", letter: "J" },
    b: { text: "计划太死，错过突然冒出来的新机会。", letter: "P" },
  },
  {
    axis: "E / I",
    text: "如果策略赚钱了，你更想？",
    a: { text: "和别人交流这个判断为什么奏效。", letter: "E" },
    b: { text: "自己安静复盘，看看是否能重复。", letter: "I" },
  },
  {
    axis: "S / N",
    text: "你更像哪种交易者？",
    a: { text: "先看事实，再谈想象。", letter: "S" },
    b: { text: "先看可能性，再找证据验证。", letter: "N" },
  },
  {
    axis: "T / F",
    text: "当模型结果和直觉冲突时，你更可能？",
    a: { text: "先信模型，再检查输入哪里可能错。", letter: "T" },
    b: { text: "先听听直觉，再判断模型是否漏了人的因素。", letter: "F" },
  },
  {
    axis: "J / P",
    text: "你最舒服的交易节奏是？",
    a: { text: "有计划地等待、执行、复盘。", letter: "J" },
    b: { text: "边走边看，市场给什么牌就打什么牌。", letter: "P" },
  },
];
